### ISSUE TITLE
14cm炮的初始装备和属性加成有误

### ISSUE THREAD

**Issue by sinsinpub** [TeamFleet/WhoCallsTheFleet#100]
整理更新数据时发现以下问题：

* 夕张**改**的初始装备第二期开始从 14cm**单**装炮 变成了 14cm**连**装炮。（非改的单装炮不变）
![image](https://user-images.githubusercontent.com/160240/50745853-52b47380-1267-11e9-9ec4-71159c6bc5df.png)
![image](https://user-images.githubusercontent.com/160240/50745870-5f38cc00-1267-11e9-98fd-9672bbc11d16.png)
* 现在 14cm**单**装炮 上的属性加成全部属于 14cm**连**装炮。单装炮我自己试了一下在夕张和夕张改上都没有任何加成。
![image](https://user-images.githubusercontent.com/160240/50745932-ad4dcf80-1267-11e9-9766-392785e4effb.png)

**Comment by Diablohu** [comment]
fixed in https://github.com/TeamFleet/WhoCallsTheFleet-DB/commit/fd3b4a6a78483ff8734912d069388c3ba3bc3554 and https://github.com/TeamFleet/KCKit/commit/99e8d24c87184ba47805937b2ef2a3d99911f59c
