### ISSUE TITLE
Web版，无限漂船loading动画，Ctrl+F5 刷新也没效果

### ISSUE THREAD

**Issue by sandwichii** [TeamFleet/WhoCallsTheFleet#101]
浏览器是Google Chrome 71.0.3578.98（正式版本） （64 位）

直接连接
没发现和插件的冲突
隐身模式能正常访问
Console无报错
用能显示加载进度条的插件发现资源能全部加载完毕

**Comment by Diablohu** [comment]
看描述应该是cookie或是本地数据存储有损坏，可以使用以下方法尝试修复

1. 访问Web版，打开Web开发者工具 (Windows系统下按F12)
2. 开发者工具顶部标签页切换到 `Application` (如果没有看到，可以点击右边的 `>>` 菜单，里面应该有这一项)
3. 将左侧菜单中的 `Local Storage` 项目展开
4. 在 `http://fleet.diablohu.com` 上按右键，选择 `Clear`
    - 该操作会将Web版内的所有设置清除并重置
    - 舰队数据不会受影响

如果上述操作仍未解决问题，可以尝试使用以下方法完全重置数据并恢复舰队模拟数据

1. 访问Web版，打开Web开发者工具 (Windows系统下按F12)
2. 开发者工具顶部标签页切换到 `Console` (或按 `ESC` 键可呼出控制台)
3. 在控制台中粘贴以下代码
```javascript
const request = indexedDB.open('NeDB');
request.onsuccess = function(evt) {
    const db = evt.target.result;
    db.transaction(["nedbdata"], "readwrite")
        .objectStore("nedbdata")
        .get("fleets")
        .onsuccess = function(evt) {
            const blob = new Blob([evt.target.result], {type: "text/plain;charset=utf-8"});
            const link = document.createElement('a');
            const url = URL.createObjectURL(blob);
            link.href = url;
            link.download = 'fleets-backup.json';
            document.body.appendChild(link);
            link.click();
            setTimeout(function() {
                document.body.removeChild(link);
                window.URL.revokeObjectURL(url);  
            }, 0)
        };
};
```
4. 按回车运行上述代码
    - 上述代码会尝试对已有的舰队数据进行备份，会自动在你的下载目录中建立 `fleets-backup.json` 文件
5. 开发者工具顶部标签页切换到 `Application` (如果没有看到，可以点击右边的 `>>` 菜单，里面应该有这一项)
6. 在左侧菜单中选择 `Clear storage`
7. 右侧面板拉到底部，按下 `Clear site data`
8. 关闭Web版当前页面，重新访问
9. 在舰队模拟页面中，按下 `新建/导入`，选择 `导入配置文件`，选择 `步骤4` 中备份的文件，即可将舰队数据恢复

**Comment by sandwichii** [comment]
没起到作用

**Comment by Diablohu** [comment]
那么多半是某个插件冲突了……

隐身模式就是把所有数据都清掉、默认不加载插件的干净环境
