### ISSUE TITLE
鈴熊航改二速力錯誤

### ISSUE THREAD

**Issue by akimizuken** [TeamFleet/WhoCallsTheFleet#104]
如圖
![NG](https://user-images.githubusercontent.com/50686516/57821760-45366980-77c4-11e9-9d70-0bf469d9eb85.png)

**Comment by Diablohu** [comment]
多谢提出

**Comment by Diablohu** [comment]
fix in https://github.com/TeamFleet/WhoCallsTheFleet-DB/commit/9cea4eed9009293bc017e3309cdb03c40dca4e3f
