### ISSUE TITLE
想问下游戏的一些数据是怎么获取的

### ISSUE THREAD

**Issue by GodRuiCollection** [TeamFleet/WhoCallsTheFleet#107]
最近在学前端后台 想试着写些游戏工具 但是苦于游戏数据获取
比如每个舰娘可以带哪些装备 特殊装备加成 每个装备改修后的提升 基础运 最高运 这些数据是可以抓取的吗 有缓存在本地的json之类吗？还是我只能等其它人的数据  
因为没有找到有人在论坛提到这些事 所以来打扰下

**Comment by Diablohu** [comment]
舰娘默认装备：手工整理
特殊装备加成：手工整理
改修收益：手工整理
基础运、最高运：存在于可抓取的游戏数据内 (api_start2)

**Comment by GodRuiCollection** [comment]
我去试试 感谢
