### ISSUE TITLE
macOS 10.15.5版本 无法打开应用

### ISSUE THREAD

**Issue by ColorValue** [TeamFleet/WhoCallsTheFleet#112]
第一打开应用（版本v0.30.40）提示 “应用程序“nwjs”无法打开”，/Users/[你的用户名]/Library/Application Support/WhoCallsTheFleet 也没有找到该文件夹

**Comment by ColorValue** [comment]
找到问题解决，不要用访达自带的解压，用第三方解压器解压比如Bandizip这类软件的解压就正常打开

**Comment by Diablohu** [comment]
> 找到问题解决，不要用访达自带的解压，用第三方解压器解压比如Bandizip这类软件的解压就正常打开

……这都行？
