### ISSUE TITLE
Several inconsistent Akashi improvement info

### ISSUE THREAD

**Issue by sinsinpub** [TeamFleet/WhoCallsTheFleet#115]
1. `九七式艦攻改 試製三号戊型(空六号電探改装備機)` should improvable on Tuesday
![image](https://user-images.githubusercontent.com/160240/93011608-2ddeda80-f5ca-11ea-94d8-a30229a80e96.png)

![image](https://user-images.githubusercontent.com/160240/93011612-3b946000-f5ca-11ea-8b45-056948998b32.png)

2. `三式弾` should not on Saturday by `比叡改二丙`
![image](https://user-images.githubusercontent.com/160240/93011652-93cb6200-f5ca-11ea-9de8-3b18b2818933.png)

![image](https://user-images.githubusercontent.com/160240/93011658-a04fba80-f5ca-11ea-9a48-183c007b833e.png)

**Comment by Diablohu** [comment]
fixed https://github.com/TeamFleet/WhoCallsTheFleet-DB/commit/66b4f6e6767dc0469cd51575eb95a83414c2d6d9

**Comment by sinsinpub** [comment]
其实还有两类：
1. 新实装的加贺改二/戊/护ID没有加上。可改修项和原型/改一样。
![image](https://user-images.githubusercontent.com/160240/93969666-02fd3f00-fd9f-11ea-849f-8aefaa75be00.png)
2. `二式12cm迫撃砲改`据说只有日进**甲**可以，原型和改没有。akashi-list.me也这么表示。没有船我没法确认。
![image](https://user-images.githubusercontent.com/160240/93969730-24f6c180-fd9f-11ea-984d-4825eca8f79c.png)
  还有新增改修的`甲標的 甲型`也只有到**改**的报告，原型不知可不可以。
![image](https://user-images.githubusercontent.com/160240/93969972-b108e900-fd9f-11ea-970c-8b1a44290af0.png)

**Comment by Diablohu** [comment]
`二式12cm迫撃砲改` 按照 https://twitter.com/KC_KaishuBot 他的统计，日进的 3 个形态都可以

fixed https://github.com/TeamFleet/WhoCallsTheFleet-DB/commit/988bc2029bc83cb81cc33478ea6ddf4cd2f91aad

**Comment by sinsinpub** [comment]
新发现两个改修ID上的小问题，不知该不该开新issue好。。。

1. `Aquila改`的ID 365错打成`大鹰改`的380了
![image](https://user-images.githubusercontent.com/160240/103797990-1b5e4480-5084-11eb-9571-1f25ee9036a6.png)
2. `零式艦戦52型`应该可以用`瑞鶴改二甲`
![image](https://user-images.githubusercontent.com/160240/103798246-637d6700-5084-11eb-8eea-1922cbab2f68.png)
![image](https://user-images.githubusercontent.com/160240/103798587-e0a8dc00-5084-11eb-8e84-3fa3d8254f6f.png)

**Comment by Diablohu** [comment]
fixed https://github.com/TeamFleet/WhoCallsTheFleet-DB/commits/master
