### ISSUE TITLE
秋云改二的装备加成计算存在bug

### ISSUE THREAD

**Issue by ykxakks** [TeamFleet/WhoCallsTheFleet#117]
在“是谁呼叫舰队”网站上的“舰队”页面，给秋云改二装备12.7cm连装炮D型改三+12.7cm连装炮D型改二+GFCS电探+熟练见张员（补强增设）时，面板总火力显示为92，实际游戏中测试为90.

去除电探后，面板火力显示为83，实际游戏中为81. 测试时使用html5网页版，未测试安卓版是否不同。

初步推断是游戏中D3炮，D2炮与见张的加成只计算一次但插件计算2次导致。

感谢学霸（微博@长门厨_迫真）的测试（和500日元经费）。

**Comment by Diablohu** [comment]
![image](https://user-images.githubusercontent.com/1946774/100484942-48d8d980-3139-11eb-88eb-dd6faea8f52f.png)

有点难看，不过这样数据是对的
