### ISSUE TITLE
神州丸改修大發動艇消耗裝備錯漏

### ISSUE THREAD

**Issue by Jurrunio** [TeamFleet/WhoCallsTheFleet#122]
現在顯示為轉換前都不需要消耗裝備，實際上跟其他艦娘一樣改修大發需要用桶/機槍才對

**Comment by Diablohu** [comment]
fixed in https://github.com/TeamFleet/WhoCallsTheFleet-DB/commit/2cfe222f3fc550deaec56163cdb603345066d295
