### ISSUE TITLE
最新增加的局战/陆战（台南空航空队），疑似不能正确计算制空值

### ISSUE THREAD

**Issue by mathyyj** [TeamFleet/WhoCallsTheFleet#126]
最新增加的局战/陆战，疑似不能正确计算制空值，

指最近活动给的021台南，022台南，032台南

期待能修复

**Comment by Diablohu** [comment]
fixed https://github.com/TeamFleet/WhoCallsTheFleet/commit/85e96aa1184bd1e2d7cdfbe6198aa5aa6c4c04dd
