### ISSUE TITLE
客戶端生成的配置連接有誤。

### ISSUE THREAD

**Issue by SkywalkerJi** [TeamFleet/WhoCallsTheFleet#130]
生成后在瀏覽器中為空配置。

測試數據：
`
{"version":4,"f1":{"s1":{"id":646,"lv":139,"luck":24,"items":{"i1":{"id":144,"rf":0,"mas":7},"i2":{"id":244,"rf":0,"mas":0},"i3":{"id":100,"rf":0,"mas":7},"i4":{"id":336,"rf":0,"mas":7},"ix":{"id":33,"rf":0,"mas":0},"i5":{"id":87,"rf":0,"mas":0}}},"s2":{"id":599,"lv":174,"luck":39,"items":{"i1":{"id":144,"rf":0,"mas":7},"i2":{"id":94,"rf":0,"mas":7},"i3":{"id":100,"rf":0,"mas":7},"i4":{"id":437,"rf":0,"mas":7},"ix":{"id":33,"rf":0,"mas":0},"i5":{"id":87,"rf":0,"mas":0}}},"s3":{"id":119,"lv":174,"luck":50,"items":{"i1":{"id":262,"rf":0,"mas":0},"i2":{"id":364,"rf":0,"mas":0},"i3":{"id":87,"rf":0,"mas":0},"i4":{"id":33,"rf":0,"mas":0}}},"s4":{"id":554,"lv":140,"luck":46,"items":{"i1":{"id":327,"rf":0,"mas":7},"i2":{"id":212,"rf":0,"mas":7},"i3":{"id":157,"rf":10,"mas":7},"i4":{"id":87,"rf":0,"mas":0},"ix":{"id":33,"rf":0,"mas":0},"i5":{"id":87,"rf":0,"mas":0}}},"s5":{"id":466,"lv":174,"luck":24,"items":{"i1":{"id":100,"rf":0,"mas":7},"i2":{"id":144,"rf":0,"mas":7},"i3":{"id":94,"rf":0,"mas":0},"i4":{"id":87,"rf":0,"mas":0},"ix":{"id":33,"rf":0,"mas":0}}},"s6":{"id":467,"lv":174,"luck":56,"items":{"i1":{"id":154,"rf":0,"mas":7},"i2":{"id":144,"rf":0,"mas":7},"i3":{"id":94,"rf":0,"mas":0},"i4":{"id":87,"rf":0,"mas":0},"ix":{"id":33,"rf":0,"mas":0}}}},"f2":{},"f3":{},"f4":{},"fField":{}}
`

生成鏈接：
`http://fleet.diablohu.com/fleets/build/?i=IQxZfofZglHO8Lvd&d=N4IgJghgLhIFwG0kDYAsyA0CCMBmAnBgEyoC6W2qqxVG2ADPRrrpixgBwDs5CvXGAHYBXADaiMAnrwCs%2BQji7UCvStXzUGTVLgHtuvfpOPSK2BdiUYZ9XkWRFmaTgJHjmuQ1lKyZ1HKjayLy4RAJE2I7YMgLcHi68bhJJdLZYUpI%2BWOiYitQkqox0tBouHl4IUlkI6AJ51sEUfsXq1HEsFVXVFYbkIAAWAI4A%2BqIAbvAAtNgYIIIQALYApvAgRPQRAASA056bAKLY05uAG1mA%2BAkA1JuA0HKA97Egs4IA9lArcCD3IFD9S8vwuAC%2BQA`

![image](https://user-images.githubusercontent.com/22220678/139670007-40e313fc-344e-48be-a38f-b6c679490b9c.png)
![image](https://user-images.githubusercontent.com/22220678/139670030-7b5ed9a0-5388-439b-869e-cf73f30c5500.png)

**Comment by Diablohu** [comment]
已修正
