### ISSUE TITLE
网页端二式爆雷改二的蓝字不完全

### ISSUE THREAD

**Issue by slagwave** [TeamFleet/WhoCallsTheFleet#142]
部分DE带二式爆雷改二 对潜和回避也会+1
目前试下来有
占守型 改后
择捉型 改后
日振型 改后
鹈来型 改后
丁型海防舰 改后

其实就是除了御藏型的DE以外的都有对潜和回避的+1蓝字

**Comment by Diablohu** [comment]
fixed https://github.com/TeamFleet/KCKit/commit/6070e93fedb7a45ce67d296c5c9a9eef94f85e48
