### ISSUE TITLE
0.34版本一直更新失败，百度网盘该版本文件为空，无法下载

### ISSUE THREAD

**Issue by VOLVOSUNWIN** [TeamFleet/WhoCallsTheFleet#144]

**Comment by Diablohu** [comment]
抱歉前一阵一直在忙工作，最近才有空排查这一问题，已解决

**Comment by VOLVOSUNWIN** [comment]
好诶，清霜刚改二，还请继续更新哦
________________________________
发件人: Diablohu ***@***.***>
发送时间: 2023年10月17日 13:26
收件人: TeamFleet/WhoCallsTheFleet ***@***.***>
抄送: VOLVOSUNWIN ***@***.***>; Author ***@***.***>
主题: Re: [TeamFleet/WhoCallsTheFleet] 0.34版本一直更新失败，百度网盘该版本文件为空，无法下载 (Issue #144)


抱歉前一阵一直在忙工作，最近才有空排查这一问题，已解决

―
