### ISSUE TITLE
建议增加装备拖拽功能

### ISSUE THREAD

**Issue by Sunsetra** [TeamFleet/WhoCallsTheFleet#26]
新增的舰娘搜索功能很不错啊，作者辛苦了~~

另外就是给舰娘选装备时经常有相同装备，希望可以只在列表选择一次，然后其他相同装备可以拖拽复制到其他格或者其他舰娘身上~~

**Comment by xingxuanma** [comment]
还有就是想移动装备时也可以这样随机拖拽已经装上的装备就好了~

**Comment by Diablohu** [comment]
多谢提议
