### ISSUE TITLE
遨游浏览器进不去 一直卡在黄色小船那 

### ISSUE THREAD

**Issue by 2823974468** [TeamFleet/WhoCallsTheFleet#82]

**Comment by Diablohu** [comment]
遨游版本？

**Comment by 2823974468** [comment]
4.4.8.1000 不知道是不是最新的 貌似最新的也不行

**Comment by 2823974468** [comment]
4.4.8.1000 不知道是不是最新的 貌似最新的也不行

**Comment by Diablohu** [comment]
![image](https://user-images.githubusercontent.com/1946774/30852581-d54edf6e-a2de-11e7-9dc9-b85a16ef77fa.png)

**Comment by 2823974468** [comment]
那我升级下看看吧
