### ISSUE TITLE
水無月 missing romaji

### ISSUE THREAD

**Issue by DynamicSTOP** [TeamFleet/WhoCallsTheFleet#84]
Hi!
Can i ask you to add **ja_romaji** for 水無月? 
https://github.com/TeamFleet/WhoCallsTheFleet/blob/4653d8ffba30daedc96c22f18e7fed6f4eaedf52/app-db/ships.nedb#L441
Thanks!

**Comment by Diablohu** [comment]
thanks
will fix in next batch of update

**Comment by Diablohu** [comment]
fixed in https://github.com/TeamFleet/WhoCallsTheFleet-DB/commit/261f0285caa948d6bdec665862838fe2c9921a01

**Comment by DynamicSTOP** [comment]
Thanks!
