### ISSUE TITLE
[改修数据]25mm連装機銃 缺少 文月改二

### ISSUE THREAD

**Issue by KagamiChan** [TeamFleet/WhoCallsTheFleet#86]
如题，文月改二没有出现在秘书舰当中
![image](https://user-images.githubusercontent.com/3816900/34649339-43cfdb64-f3e8-11e7-9c1b-ff11b96a0edf.png)

**Comment by KagamiChan** [comment]
虽然和 issue 无关了，poi 的数据汇报现在已经在收集改修数据，对数据更新和验证也许有所帮助（虽然现在还没有把 useitem 的数据收集加进去）
https://github.com/poooi/poi-server/wiki#item-remodel-recipe

**Comment by sinsinpub** [comment]
打算把改修汇报也加入KC3改。。。
@KagamiChan 既然跑题了，那么顺便问一下哪里可以匿名查询到收集到的数据呢？
另外，汇报接口中的DoW需要的数值是从0开始还是从1？从星期天开始还是从星期一？
`note that 101, 201, 301 will not be reported` 这句的意思其实是“希望不要汇报这几条”么？
汇报接口中不需要成功标志`api_remodel_flag`的样子，也就是说不打算统计"成功率“咯？

**Comment by KagamiChan** [comment]
@sinsinpub 这个收集只是收集改修配方，不收集改修成功率。以前收集过一次成功率在[这里](https://bbs.ngacn.cc/read.php?tid=9494956&rand=385)。

为了避免重复收集相同数据，所以对于每个数据都有一个特殊的 id 来做标记，客户端处会从服务器端获取一个已知数据列表，只有收集到新数据才会上报。
101， 201 和 301 这三个不限定秘书舰，数据清洗比较麻烦，所以就不收集了

stage 3 是笔误，多谢指出

具体实现可以看这里 https://github.com/poooi/plugin-report/blob/master/index.es#L339

**Comment by KagamiChan** [comment]
P.S. 从过去数据收集的情况看，目前 poi 的用户规模已经差不多能收集全，所以不实现这个收集也可以。另外由于这个改修是基于改修配方的，不好自动生成基于装备的改修数据（有一些特例情况比较难以处理），因此只能作为检验使用 - -

**Comment by Diablohu** [comment]
无论怎么说，这种级别的黑盒的数据，最后还得经过一次人工 😕

**Comment by Diablohu** [comment]
fixed
