### ISSUE TITLE
建议：可否在配装界面拆分飞行器列？

### ISSUE THREAD

**Issue by CopsiTG** [TeamFleet/WhoCallsTheFleet#88]
背景：在使用“WhoCallsTheFleet”配置并参考陆航制空能力时，因为需要较频繁更换陆航飞机，而飞行器列中陆航飞机大部位于偏下的位置，导致操作较为繁琐。
建议：能否至少在使用陆航配置打开“飞行器”列表时，对列表进行一定程度的拆分，比如分两列分别显示舰载机和陆航&其他。
个人拙见。

**Comment by Diablohu** [comment]
这个问题我也有考虑，不过我更倾向于在配置陆航时，陆航相关飞机直接放开头

**Comment by CopsiTG** [comment]
嗯，这样也挺好的。
顺带一提，在0.26.2版本中，紫电改（三四三空）战斗301显示的属性是+3迎击，而在游戏图鉴中是+4迎击

**Comment by Diablohu** [comment]
解决方案：在配置陆航时，会直接定位到大艇
