### ISSUE TITLE
改修工厂 三酸後期型+6后消耗三酸个数有误

### ISSUE THREAD

**Issue by lackofdream** [TeamFleet/WhoCallsTheFleet#90]
根据 [Twitter 上的情报](https://twitter.com/yappiakmp/status/997078400731828225)，61cm三連装(酸素)魚雷後期型 +6 以后吃**一个** 61cm三连装（酸素）鱼雷，而不是三个。

**Comment by Diablohu** [comment]
fix in https://github.com/TeamFleet/WhoCallsTheFleet-DB/commit/131b0a4577f4c0b082ad979b65732f70b4c1de9b
