### ISSUE TITLE
特效装备建议

### ISSUE THREAD

**Issue by tj8m23le** [TeamFleet/WhoCallsTheFleet#92]
在装备总览界面加一栏此件装备有特别舰特效的条目 很多不看论坛官推的朋友恐怕都不知道哪个有特效

**Comment by Diablohu** [comment]
好建议！这个改动也可以用在舰娘列表里

事实上我有类似的想法，不过想的太多了，你的提议简单有效 ❤

**Comment by Diablohu** [comment]
![image](https://user-images.githubusercontent.com/1946774/41505081-306f6fe8-7233-11e8-8bec-c457f5003fa6.png)
下次更新时实装
