### ISSUE TITLE
希望能够查询舰娘在特定等级的对潜值。

### ISSUE THREAD

**Issue by XuZhilei** [TeamFleet/WhoCallsTheFleet#93]
不过似乎对潜值的数据不好推算？以前在Google文档上见过一张表列出了各个等级的反潜值，这些值是手动记录下来的吗？

**Comment by Diablohu** [comment]
正在开发的1.0版本已加入该功能（1.0版在线预览： https://yuubari.fleet.moe/ships/321 ）。目前个人计划不打算将该功能实装到现行的v0版本

对潜值成长是线性的，理论上在知道几个等级的对潜值之后，就可以算出成长
